# -*- coding: utf-8 -*-
"""codigos_aleatorios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hu0MP-6SVcInhdUxI9dUv9TgES1yriFl
"""

lista_de_letras = ['a', 'b', 'c', 'd', 'e']
contador = 1

for letra in lista_de_letras:
    print(f'{letra*contador}')
    contador += 1